# Generated by Django 4.2.2 on 2023-06-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
